name: 'publish'
on:
  push:
    branches:
      - web

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Connect to BUILD_SERVER and execute pull and build commands
        run: |
          $key = "${{ secrets.PEM_KEY }}"
          $tempPath = "temp_key.pem"
          Set-Content -Path $tempPath -Value $key
          chmod 600 $tempPath
          icacls.exe $tempPath /inheritance:r
          icacls.exe $tempPath /grant:r "${env:USERNAME}:(R)"
          ssh -i $tempPath ubuntu@54.157.111.21 -o StrictHostKeyChecking=no "
            sudo su - &&
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash &&
            export NVM_DIR=/home/ubuntu/.nvm &&
            [ -s /home/ubuntu/.nvm/nvm.sh ] && \. /home/ubuntu/.nvm/nvm.sh &&
            nvm install 21 &&
            nvm use 21 &&
            cd /var/www/html/codefend-user &&
            git pull origin build &&
            npm install &&
            npm run build"